### ISSUE TITLE
linux version don't running success

### ISSUE THREAD

**Issue by charlsmagic** [ionet-official/ProductFeedback#2]
<img width="1548" alt="image" src="https://github.com/ionet-official/ProductFeedbaxk/assets/44356145/2de630d7-9c39-480d-83ca-3bb434f8e0ad">
<img width="1175" alt="image" src="https://github.com/ionet-official/ProductFeedbaxk/assets/44356145/0ed202ba-0a12-450d-925f-a5559c7bc792">
<img width="1418" alt="image" src="https://github.com/ionet-official/ProductFeedbaxk/assets/44356145/75e086ee-1def-48ce-ac36-8d301b4680f9">

**Comment by charlsmagic** [comment]
dashboard page don't show any new worker info

**Comment by ZhijieWang** [comment]
noted. Eng team is on it.

**Comment by charlsmagic** [comment]
how long will it take? thanks

**Comment by ZhijieWang** [comment]
pls consider running the proper setup.sh script.
