### ISSUE TITLE
Some PoW logs are empty

### ISSUE THREAD

**Issue by CSeanXu** [ionet-official/ProductFeedback#8]
e.g. [log_20240510/log_20240510_001951_hashcheck_logs-with-web-gpu-anon.csv](https://github.com/ionet-official/io-net-transparent-device-metric/blob/main/log_20240510/log_20240510_001951_hashcheck_logs-with-web-gpu-anon.csv)

**Comment by ZhijieWang** [comment]
we have fixed the rate limit we had with several providers and logs are back and up to date.
